#!/bin/bash

# the number of remove AWS servers
N=2

# the number of nodes on each server
node=16

# public IPs --- This is the public IPs of AWS servers
pubIPsVar=([0]='18.167.99.158'
  [1]='43.198.227.65')

# Init all servers
 i=0; while [ $i -le $(( N-1 )) ]; do
 scp -i "/home/ubuntu/test_large.pem" /home/ubuntu/env-batch.sh ubuntu@${pubIPsVar[i]}:/home/ubuntu/  
 ssh -o "StrictHostKeyChecking no" -i "/home/ubuntu/test_large.pem" ubuntu@${pubIPsVar[i]} "chmod 777 /home/ubuntu/env-batch.sh && sudo ./env-batch.sh" &
 i=$(( i+1 ))
 done
 
# Clone code,config and keys to all remote AWS servers from github
 i=0; while [ $i -le $(( N-1 )) ]; do
 ssh -o "StrictHostKeyChecking no" -i "/home/ubuntu/test_large.pem" ubuntu@${pubIPsVar[i]} "git clone --branch speed-kronos https://github.com/hidden-er/kronos.git"
 done
